// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd5771SAbEihCyVh0ETAOjpleRzUguSaU',
    appId: '1:538090264792:web:4c0e05280366beea8e1fad',
    messagingSenderId: '538090264792',
    projectId: 'fir-5c1e2',
    authDomain: 'fir-5c1e2.firebaseapp.com',
    storageBucket: 'fir-5c1e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsZ4CnrtmlwM9xQJOTYhaq9jSTbuwELwE',
    appId: '1:538090264792:android:a2beeec02d4ad12e8e1fad',
    messagingSenderId: '538090264792',
    projectId: 'fir-5c1e2',
    storageBucket: 'fir-5c1e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-vjp-Lp3YsQ9-VNOtI2XtlIHSC3xNKJc',
    appId: '1:538090264792:ios:9e1bcadbebe923118e1fad',
    messagingSenderId: '538090264792',
    projectId: 'fir-5c1e2',
    storageBucket: 'fir-5c1e2.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );
}
